# Generated by Django 3.0.8 on 2020-07-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ava', models.ImageField(blank=True, null=True, upload_to='')),
                ('status', models.TextField()),
                ('country', models.CharField(max_length=50)),
                ('town', models.CharField(max_length=50)),
                ('subscriptionsStatus', models.BooleanField()),
                ('friendsCount', models.IntegerField()),
                ('subscribersCount', models.IntegerField()),
                ('photosCount', models.IntegerField()),
                ('audiosCount', models.IntegerField()),
            ],
        ),
    ]
